import type { Locale } from "./config";

const en = {
  stays:"Stays",changeSearch:"Change search",searching:"Searching…",invalidSearch:"Invalid search.",loadStaysError:"Something went wrong loading stays. Please try again shortly.",noStays:"No stays match your search. Try different dates or a different destination.",night:"night",guest:"guest",guests:"guests",bed:"bed",beds:"beds",bath:"bath",baths:"baths",
  loadingTrips:"Loading your trips…",signInTrips:"Sign in to see your trips.",signIn:"Sign in",loadTripsError:"Something went wrong loading your trips. Please try again shortly.",myTrips:"My Trips",browseDestinations:"Browse destinations",noTrips:"No trips yet.",startExploring:"Start exploring stays.",upcoming:"Upcoming",past:"Past",cancelledRefunded:"Cancelled / Refunded",resumePayment:"Resume payment",reviewPayment:"Review payment",viewTrip:"View trip",
  loadingCheckout:"Loading checkout…",bookingLoadError:"Could not load this booking.",serverError:"Could not reach the server.",checkoutStartError:"Could not start checkout.",stripeTest:"Stripe test mode",savePaymentMethod:"Save your payment method",completeBooking:"Complete your booking",deferredChargePrefix:"Your card will be saved securely and charged automatically on",immediateSavedCharge:"Your card will be saved securely and charged for this booking immediately after confirmation.",reviewPaymentDetails:"Review your payment details and complete your booking securely.",loadingPayment:"Loading secure payment form…",saving:"Saving…",processing:"Processing…",saveCardPay:"Save card and pay",payNow:"Pay now",savePaymentFailed:"Could not save your payment method. Please try again.",paymentFailed:"Payment failed. Please try again.",notChargedTodayPrefix:"Your card won't be charged today. It will be charged automatically on",scheduledDate:"the scheduled payment date",chargedImmediately:"Your card will be charged for this booking immediately after you save and confirm it.",
  reviewsHeading:"Reviews",oneReview:"review",manyReviews:"reviews",loadingReviews:"Loading reviews…",loadReviewsError:"Couldn't load reviews right now.",noReviews:"No reviews yet — be the first to stay and share your experience.",reviewerGuest:"Guest",hostResponse:"Host response",showMoreReviews:"Show more reviews",cleanliness:"Cleanliness",location:"Location",accuracy:"Accuracy",communication:"Communication",comfort:"Comfort",compliancePending:"The property's compliance information has not yet completed HOST review.",complianceReviewed:"The owner supplied compliance declarations and supporting evidence reviewed by HOST. The owner remains responsible for the property and for keeping all checks current.",
  loadingTrip:"Loading trip…",signInViewTrip:"Sign in to view this trip.",tripUnavailable:"This trip isn't available.",loadTripError:"Something went wrong loading this trip. Please try again shortly.",completePaymentSetup:"Complete payment setup",priceBreakdown:"Price breakdown",accommodation:"Accommodation",serviceFee:"Service fee",taxes:"Taxes",totalPaid:"Total paid",bookingTotal:"Booking total",refundStatus:"Refund status",cancelBooking:"Cancel booking",checking:"Checking…",tripHistory:"Trip history",refund:"Refund",refundAmount:"Refund amount",amountRetained:"Amount retained",keepBooking:"Keep booking",cancelling:"Cancelling…",confirmCancellation:"Confirm cancellation",cannotCancel:"Can't cancel this booking",close:"Close",
  confirmingPayment:"Confirming your payment…",almostThere:"Almost there",confirmationAutomatic:"This updates automatically once your payment is confirmed — this usually takes just a few seconds.",paymentMethodSaved:"Payment method saved",allSetForNow:"You're all set — for now",savedMethodPrefix:"We've securely saved your payment method. Your card will be charged automatically on",closerDate:"a date closer to your check-in",savedMethodSuffix:"ahead of your stay — you don't need to do anything else right now.",paymentAttention:"Payment needs attention",cardNotCharged:"Your card was not charged",attemptDeclined:"Your payment attempt was declined.",updatePayment:"Update payment method",longerExpected:"Taking longer than expected",waitingConfirmation:"We're still waiting on confirmation",checkTripStatus:"Check trip status",bookingConfirmed:"Booking confirmed",allSet:"You're all set.",reference:"Reference",nights:"Nights",bookingStatus:"Booking status",paymentStatus:"Payment status",amountPaid:"Amount paid",
  previous:"Prev",next:"Next",manuallyBlocked:"Manually blocked",bookedByGuest:"Booked by guest",available:"Available",paymentFormLoadError:"The secure payment form could not load. No payment was taken.",reloadPaymentForm:"Reload secure payment form",testCardNote:"Test Mode — use Stripe's official test cards (e.g. 4242 4242 4242 4242), never a real card.",
  backSearch:"Back to search",reviews:"reviews",bedroom:"bedroom",bedrooms:"bedrooms",bathroom:"bathroom",bathrooms:"bathrooms",informationalPrice:"Informational only — your exact total is calculated at booking.",notChargedYet:"You won't be charged yet. Pricing and availability are confirmed on the next step.",
  loadingStay:"Loading stay…",stayNotFound:"Stay not found",mayUnavailable:"This property may no longer be available.",loadStayError:"Something went wrong loading this stay. Please try again shortly.",stay:"Stay",aboutStay:"About this stay",checkInOut:"Check-in & check-out",checkInFrom:"Check-in from",checkOutBy:"Check-out by",houseRules:"House rules",propertyCompliance:"Property compliance",ownerEvidenceReviewed:"Owner evidence reviewed",reviewPending:"Review pending",lastReviewed:"Last reviewed",applicableChecks:"applicable checks",cancellationPolicy:"Cancellation policy",selectDate:"Select a date",fullName:"Full name",email:"Email",cleaningFee:"Cleaning fee",estimatedTotal:"Estimated total",reserving:"Reserving…",reserve:"Reserve",datesBooked:"Those dates were just booked by someone else. Please choose different dates.",createBookingError:"Couldn't create the booking. Please try again.",reachingServerError:"Something went wrong reaching the server. Please try again.",checkIn:"Check-in",checkOut:"Check-out",
  save:"Save",saved:"Saved",saveThisStay:"Save this stay",removeSavedStay:"Remove this stay from your saved list",saveUpdateError:"Unable to update saved stays. Please try again.",
};
export type GuestMessageKey = keyof typeof en;
type GuestDictionary = Record<GuestMessageKey,string>;

const de: GuestDictionary = {
  stays:"Unterkünfte",changeSearch:"Suche ändern",searching:"Suche läuft…",invalidSearch:"Ungültige Suche.",loadStaysError:"Unterkünfte konnten nicht geladen werden. Bitte versuchen Sie es später erneut.",noStays:"Keine Unterkunft entspricht Ihrer Suche. Versuchen Sie andere Daten oder ein anderes Reiseziel.",night:"Nacht",guest:"Gast",guests:"Gäste",bed:"Bett",beds:"Betten",bath:"Bad",baths:"Bäder",
  loadingTrips:"Ihre Reisen werden geladen…",signInTrips:"Melden Sie sich an, um Ihre Reisen zu sehen.",signIn:"Anmelden",loadTripsError:"Ihre Reisen konnten nicht geladen werden. Bitte versuchen Sie es später erneut.",myTrips:"Meine Reisen",browseDestinations:"Reiseziele entdecken",noTrips:"Noch keine Reisen.",startExploring:"Unterkünfte entdecken.",upcoming:"Bevorstehend",past:"Vergangen",cancelledRefunded:"Storniert / Erstattet",resumePayment:"Zahlung fortsetzen",reviewPayment:"Zahlung prüfen",viewTrip:"Reise ansehen",
  loadingCheckout:"Kasse wird geladen…",bookingLoadError:"Diese Buchung konnte nicht geladen werden.",serverError:"Der Server ist nicht erreichbar.",checkoutStartError:"Die Zahlung konnte nicht gestartet werden.",stripeTest:"Stripe-Testmodus",savePaymentMethod:"Zahlungsmethode speichern",completeBooking:"Buchung abschließen",deferredChargePrefix:"Ihre Karte wird sicher gespeichert und automatisch belastet am",immediateSavedCharge:"Ihre Karte wird sicher gespeichert und direkt nach der Bestätigung für diese Buchung belastet.",reviewPaymentDetails:"Prüfen Sie Ihre Zahlungsdaten und schließen Sie die Buchung sicher ab.",loadingPayment:"Sicheres Zahlungsformular wird geladen…",saving:"Speichern…",processing:"Verarbeitung…",saveCardPay:"Karte speichern und bezahlen",payNow:"Jetzt bezahlen",savePaymentFailed:"Ihre Zahlungsmethode konnte nicht gespeichert werden. Bitte versuchen Sie es erneut.",paymentFailed:"Zahlung fehlgeschlagen. Bitte versuchen Sie es erneut.",notChargedTodayPrefix:"Ihre Karte wird heute nicht belastet. Sie wird automatisch belastet am",scheduledDate:"geplanten Zahlungstag",chargedImmediately:"Ihre Karte wird direkt belastet, nachdem Sie sie gespeichert und bestätigt haben.",
  reviewsHeading:"Bewertungen",oneReview:"Bewertung",manyReviews:"Bewertungen",loadingReviews:"Bewertungen werden geladen…",loadReviewsError:"Bewertungen können derzeit nicht geladen werden.",noReviews:"Noch keine Bewertungen — seien Sie der erste Gast und teilen Sie Ihre Erfahrung.",reviewerGuest:"Gast",hostResponse:"Antwort des Gastgebers",showMoreReviews:"Weitere Bewertungen anzeigen",cleanliness:"Sauberkeit",location:"Lage",accuracy:"Genauigkeit",communication:"Kommunikation",comfort:"Komfort",compliancePending:"Die Compliance-Informationen dieser Unterkunft wurden noch nicht vollständig von HOST geprüft.",complianceReviewed:"HOST hat die Erklärungen und Nachweise des Eigentümers geprüft. Der Eigentümer bleibt für die Unterkunft und die Aktualität aller Prüfungen verantwortlich.",
  loadingTrip:"Reise wird geladen…",signInViewTrip:"Melden Sie sich an, um diese Reise anzusehen.",tripUnavailable:"Diese Reise ist nicht verfügbar.",loadTripError:"Diese Reise konnte nicht geladen werden. Bitte versuchen Sie es später erneut.",completePaymentSetup:"Zahlungseinrichtung abschließen",priceBreakdown:"Preisübersicht",accommodation:"Unterkunft",serviceFee:"Servicegebühr",taxes:"Steuern",totalPaid:"Gesamtbetrag bezahlt",bookingTotal:"Buchungssumme",refundStatus:"Erstattungsstatus",cancelBooking:"Buchung stornieren",checking:"Prüfung…",tripHistory:"Reiseverlauf",refund:"Erstattung",refundAmount:"Erstattungsbetrag",amountRetained:"Einbehaltener Betrag",keepBooking:"Buchung behalten",cancelling:"Stornierung…",confirmCancellation:"Stornierung bestätigen",cannotCancel:"Diese Buchung kann nicht storniert werden",close:"Schließen",
  confirmingPayment:"Zahlung wird bestätigt…",almostThere:"Fast geschafft",confirmationAutomatic:"Diese Seite aktualisiert sich automatisch, sobald Ihre Zahlung bestätigt wurde — normalerweise dauert das nur wenige Sekunden.",paymentMethodSaved:"Zahlungsmethode gespeichert",allSetForNow:"Vorerst ist alles erledigt",savedMethodPrefix:"Wir haben Ihre Zahlungsmethode sicher gespeichert. Ihre Karte wird automatisch belastet am",closerDate:"einem Datum kurz vor Ihrer Anreise",savedMethodSuffix:"vor Ihrem Aufenthalt — Sie müssen jetzt nichts weiter tun.",paymentAttention:"Zahlung erfordert Aufmerksamkeit",cardNotCharged:"Ihre Karte wurde nicht belastet",attemptDeclined:"Ihr Zahlungsversuch wurde abgelehnt.",updatePayment:"Zahlungsmethode aktualisieren",longerExpected:"Es dauert länger als erwartet",waitingConfirmation:"Wir warten noch auf die Bestätigung",checkTripStatus:"Reisestatus prüfen",bookingConfirmed:"Buchung bestätigt",allSet:"Alles erledigt.",reference:"Referenz",nights:"Nächte",bookingStatus:"Buchungsstatus",paymentStatus:"Zahlungsstatus",amountPaid:"Bezahlter Betrag",
  previous:"Zurück",next:"Weiter",manuallyBlocked:"Manuell gesperrt",bookedByGuest:"Von Gast gebucht",available:"Verfügbar",paymentFormLoadError:"Das sichere Zahlungsformular konnte nicht geladen werden. Es wurde keine Zahlung vorgenommen.",reloadPaymentForm:"Zahlungsformular neu laden",testCardNote:"Testmodus — verwenden Sie nur offizielle Stripe-Testkarten (z. B. 4242 4242 4242 4242), niemals eine echte Karte.",
  backSearch:"Zurück zur Suche",reviews:"Bewertungen",bedroom:"Schlafzimmer",bedrooms:"Schlafzimmer",bathroom:"Badezimmer",bathrooms:"Badezimmer",informationalPrice:"Nur zur Information — der genaue Gesamtpreis wird bei der Buchung berechnet.",notChargedYet:"Sie werden noch nicht belastet. Preis und Verfügbarkeit werden im nächsten Schritt bestätigt.",
  loadingStay:"Unterkunft wird geladen…",stayNotFound:"Unterkunft nicht gefunden",mayUnavailable:"Diese Unterkunft ist möglicherweise nicht mehr verfügbar.",loadStayError:"Diese Unterkunft konnte nicht geladen werden. Bitte versuchen Sie es später erneut.",stay:"Unterkunft",aboutStay:"Über diese Unterkunft",checkInOut:"An- und Abreise",checkInFrom:"Anreise ab",checkOutBy:"Abreise bis",houseRules:"Hausregeln",propertyCompliance:"Unterkunftsnachweise",ownerEvidenceReviewed:"Nachweise des Eigentümers geprüft",reviewPending:"Prüfung ausstehend",lastReviewed:"Zuletzt geprüft",applicableChecks:"anwendbare Prüfungen",cancellationPolicy:"Cancellation policy — authoritative English",selectDate:"Datum auswählen",fullName:"Vollständiger Name",email:"E-Mail",cleaningFee:"Reinigungsgebühr",estimatedTotal:"Geschätzter Gesamtpreis",reserving:"Reservierung…",reserve:"Reservieren",datesBooked:"Diese Daten wurden gerade von jemand anderem gebucht. Bitte wählen Sie andere Daten.",createBookingError:"Die Buchung konnte nicht erstellt werden. Bitte versuchen Sie es erneut.",reachingServerError:"Der Server konnte nicht erreicht werden. Bitte versuchen Sie es erneut.",checkIn:"Anreise",checkOut:"Abreise",
  save:"Speichern",saved:"Gespeichert",saveThisStay:"Diese Unterkunft speichern",removeSavedStay:"Diese Unterkunft aus Ihrer gespeicherten Liste entfernen",saveUpdateError:"Gespeicherte Unterkünfte konnten nicht aktualisiert werden. Bitte versuchen Sie es erneut.",
};

const fr: GuestDictionary = {
  stays:"Hébergements",changeSearch:"Modifier la recherche",searching:"Recherche…",invalidSearch:"Recherche invalide.",loadStaysError:"Impossible de charger les hébergements. Veuillez réessayer plus tard.",noStays:"Aucun hébergement ne correspond à votre recherche. Essayez d’autres dates ou une autre destination.",night:"nuit",guest:"voyageur",guests:"voyageurs",bed:"lit",beds:"lits",bath:"salle de bain",baths:"salles de bain",
  loadingTrips:"Chargement de vos voyages…",signInTrips:"Connectez-vous pour voir vos voyages.",signIn:"Connexion",loadTripsError:"Impossible de charger vos voyages. Veuillez réessayer plus tard.",myTrips:"Mes voyages",browseDestinations:"Découvrir les destinations",noTrips:"Aucun voyage pour le moment.",startExploring:"Découvrir des hébergements.",upcoming:"À venir",past:"Passés",cancelledRefunded:"Annulés / Remboursés",resumePayment:"Reprendre le paiement",reviewPayment:"Vérifier le paiement",viewTrip:"Voir le voyage",
  loadingCheckout:"Chargement du paiement…",bookingLoadError:"Impossible de charger cette réservation.",serverError:"Impossible de joindre le serveur.",checkoutStartError:"Impossible de démarrer le paiement.",stripeTest:"Mode test Stripe",savePaymentMethod:"Enregistrer votre moyen de paiement",completeBooking:"Finaliser votre réservation",deferredChargePrefix:"Votre carte sera enregistrée en toute sécurité et débitée automatiquement le",immediateSavedCharge:"Votre carte sera enregistrée en toute sécurité et débitée immédiatement après confirmation.",reviewPaymentDetails:"Vérifiez vos informations de paiement et finalisez votre réservation en toute sécurité.",loadingPayment:"Chargement du formulaire de paiement sécurisé…",saving:"Enregistrement…",processing:"Traitement…",saveCardPay:"Enregistrer la carte et payer",payNow:"Payer maintenant",savePaymentFailed:"Impossible d’enregistrer votre moyen de paiement. Veuillez réessayer.",paymentFailed:"Le paiement a échoué. Veuillez réessayer.",notChargedTodayPrefix:"Votre carte ne sera pas débitée aujourd’hui. Elle sera débitée automatiquement le",scheduledDate:"jour de paiement prévu",chargedImmediately:"Votre carte sera débitée immédiatement après son enregistrement et votre confirmation.",
  reviewsHeading:"Avis",oneReview:"avis",manyReviews:"avis",loadingReviews:"Chargement des avis…",loadReviewsError:"Impossible de charger les avis pour le moment.",noReviews:"Aucun avis pour le moment — soyez le premier à séjourner et à partager votre expérience.",reviewerGuest:"Voyageur",hostResponse:"Réponse de l’hôte",showMoreReviews:"Afficher plus d’avis",cleanliness:"Propreté",location:"Emplacement",accuracy:"Exactitude",communication:"Communication",comfort:"Confort",compliancePending:"Les informations de conformité de cet hébergement n’ont pas encore été entièrement vérifiées par HOST.",complianceReviewed:"HOST a vérifié les déclarations et justificatifs fournis par le propriétaire. Le propriétaire reste responsable de l’hébergement et de la mise à jour de tous les contrôles.",
  loadingTrip:"Chargement du voyage…",signInViewTrip:"Connectez-vous pour voir ce voyage.",tripUnavailable:"Ce voyage n’est pas disponible.",loadTripError:"Impossible de charger ce voyage. Veuillez réessayer plus tard.",completePaymentSetup:"Finaliser la configuration du paiement",priceBreakdown:"Détail du prix",accommodation:"Hébergement",serviceFee:"Frais de service",taxes:"Taxes",totalPaid:"Total payé",bookingTotal:"Total de la réservation",refundStatus:"Statut du remboursement",cancelBooking:"Annuler la réservation",checking:"Vérification…",tripHistory:"Historique du voyage",refund:"Remboursement",refundAmount:"Montant remboursé",amountRetained:"Montant conservé",keepBooking:"Conserver la réservation",cancelling:"Annulation…",confirmCancellation:"Confirmer l’annulation",cannotCancel:"Impossible d’annuler cette réservation",close:"Fermer",
  confirmingPayment:"Confirmation de votre paiement…",almostThere:"Presque terminé",confirmationAutomatic:"Cette page se met à jour automatiquement dès que votre paiement est confirmé — cela ne prend généralement que quelques secondes.",paymentMethodSaved:"Moyen de paiement enregistré",allSetForNow:"Tout est prêt — pour le moment",savedMethodPrefix:"Nous avons enregistré votre moyen de paiement en toute sécurité. Votre carte sera débitée automatiquement le",closerDate:"à une date proche de votre arrivée",savedMethodSuffix:"avant votre séjour — vous n’avez rien d’autre à faire pour le moment.",paymentAttention:"Le paiement nécessite votre attention",cardNotCharged:"Votre carte n’a pas été débitée",attemptDeclined:"Votre tentative de paiement a été refusée.",updatePayment:"Mettre à jour le moyen de paiement",longerExpected:"Cela prend plus de temps que prévu",waitingConfirmation:"Nous attendons toujours la confirmation",checkTripStatus:"Vérifier le statut du voyage",bookingConfirmed:"Réservation confirmée",allSet:"Tout est prêt.",reference:"Référence",nights:"Nuits",bookingStatus:"Statut de la réservation",paymentStatus:"Statut du paiement",amountPaid:"Montant payé",
  previous:"Précédent",next:"Suivant",manuallyBlocked:"Bloqué manuellement",bookedByGuest:"Réservé par un voyageur",available:"Disponible",paymentFormLoadError:"Le formulaire de paiement sécurisé n’a pas pu être chargé. Aucun paiement n’a été effectué.",reloadPaymentForm:"Recharger le formulaire de paiement",testCardNote:"Mode test — utilisez uniquement les cartes de test officielles Stripe (p. ex. 4242 4242 4242 4242), jamais une vraie carte.",
  backSearch:"Retour à la recherche",reviews:"avis",bedroom:"chambre",bedrooms:"chambres",bathroom:"salle de bain",bathrooms:"salles de bain",informationalPrice:"À titre indicatif — le total exact est calculé lors de la réservation.",notChargedYet:"Vous ne serez pas encore débité. Le prix et la disponibilité seront confirmés à l’étape suivante.",
  loadingStay:"Chargement de l’hébergement…",stayNotFound:"Hébergement introuvable",mayUnavailable:"Cet hébergement n’est peut-être plus disponible.",loadStayError:"Impossible de charger cet hébergement. Veuillez réessayer plus tard.",stay:"Hébergement",aboutStay:"À propos de cet hébergement",checkInOut:"Arrivée et départ",checkInFrom:"Arrivée à partir de",checkOutBy:"Départ avant",houseRules:"Règlement intérieur",propertyCompliance:"Conformité de l’hébergement",ownerEvidenceReviewed:"Justificatifs du propriétaire vérifiés",reviewPending:"Vérification en attente",lastReviewed:"Dernière vérification",applicableChecks:"contrôles applicables",cancellationPolicy:"Cancellation policy — authoritative English",selectDate:"Sélectionner une date",fullName:"Nom complet",email:"E-mail",cleaningFee:"Frais de ménage",estimatedTotal:"Total estimé",reserving:"Réservation…",reserve:"Réserver",datesBooked:"Ces dates viennent d’être réservées par une autre personne. Veuillez choisir d’autres dates.",createBookingError:"Impossible de créer la réservation. Veuillez réessayer.",reachingServerError:"Impossible de joindre le serveur. Veuillez réessayer.",checkIn:"Arrivée",checkOut:"Départ",
  save:"Enregistrer",saved:"Enregistré",saveThisStay:"Enregistrer cet hébergement",removeSavedStay:"Retirer cet hébergement de vos favoris",saveUpdateError:"Impossible de mettre à jour vos hébergements enregistrés. Veuillez réessayer.",
};

const es: GuestDictionary = {
  ...en,
  stays:"Alojamientos",changeSearch:"Cambiar búsqueda",searching:"Buscando…",invalidSearch:"Búsqueda no válida.",loadStaysError:"No se pudieron cargar los alojamientos. Inténtalo de nuevo más tarde.",noStays:"Ningún alojamiento coincide con tu búsqueda. Prueba otras fechas u otro destino.",night:"noche",guest:"huésped",guests:"huéspedes",bed:"cama",beds:"camas",bath:"baño",baths:"baños",
  loadingTrips:"Cargando tus viajes…",signInTrips:"Inicia sesión para ver tus viajes.",signIn:"Iniciar sesión",loadTripsError:"No se pudieron cargar tus viajes. Inténtalo de nuevo más tarde.",myTrips:"Mis viajes",browseDestinations:"Explorar destinos",noTrips:"Aún no hay viajes.",startExploring:"Explorar alojamientos.",upcoming:"Próximos",past:"Pasados",cancelledRefunded:"Cancelados / Reembolsados",resumePayment:"Continuar pago",reviewPayment:"Revisar pago",viewTrip:"Ver viaje",
  loadingCheckout:"Cargando pago…",bookingLoadError:"No se pudo cargar esta reserva.",serverError:"No se pudo contactar con el servidor.",checkoutStartError:"No se pudo iniciar el pago.",stripeTest:"Modo de prueba de Stripe",savePaymentMethod:"Guardar método de pago",completeBooking:"Completar reserva",deferredChargePrefix:"Tu tarjeta se guardará de forma segura y se cobrará automáticamente el",immediateSavedCharge:"Tu tarjeta se guardará de forma segura y se cobrará inmediatamente después de la confirmación.",reviewPaymentDetails:"Revisa tus datos de pago y completa la reserva de forma segura.",loadingPayment:"Cargando formulario de pago seguro…",saving:"Guardando…",processing:"Procesando…",saveCardPay:"Guardar tarjeta y pagar",payNow:"Pagar ahora",savePaymentFailed:"No se pudo guardar tu método de pago. Inténtalo de nuevo.",paymentFailed:"El pago ha fallado. Inténtalo de nuevo.",notChargedTodayPrefix:"Hoy no se cobrará tu tarjeta. Se cobrará automáticamente el",scheduledDate:"día de pago programado",chargedImmediately:"Tu tarjeta se cobrará inmediatamente después de guardarla y confirmar.",
  reviewsHeading:"Reseñas",oneReview:"reseña",manyReviews:"reseñas",loadingReviews:"Cargando reseñas…",loadReviewsError:"No se pueden cargar las reseñas en este momento.",noReviews:"Aún no hay reseñas — sé la primera persona en alojarte y compartir tu experiencia.",reviewerGuest:"Huésped",hostResponse:"Respuesta del anfitrión",showMoreReviews:"Mostrar más reseñas",cleanliness:"Limpieza",location:"Ubicación",accuracy:"Exactitud",communication:"Comunicación",comfort:"Comodidad",compliancePending:"La información de cumplimiento de este alojamiento aún no ha sido revisada completamente por HOST.",complianceReviewed:"HOST ha revisado las declaraciones y pruebas aportadas por el propietario. El propietario sigue siendo responsable del alojamiento y de mantener todas las comprobaciones actualizadas.",
  loadingTrip:"Cargando viaje…",signInViewTrip:"Inicia sesión para ver este viaje.",tripUnavailable:"Este viaje no está disponible.",loadTripError:"No se pudo cargar este viaje. Inténtalo de nuevo más tarde.",completePaymentSetup:"Completar configuración del pago",priceBreakdown:"Desglose del precio",accommodation:"Alojamiento",serviceFee:"Comisión de servicio",taxes:"Impuestos",totalPaid:"Total pagado",bookingTotal:"Total de la reserva",refundStatus:"Estado del reembolso",cancelBooking:"Cancelar reserva",checking:"Comprobando…",tripHistory:"Historial del viaje",refund:"Reembolso",refundAmount:"Importe del reembolso",amountRetained:"Importe retenido",keepBooking:"Mantener reserva",cancelling:"Cancelando…",confirmCancellation:"Confirmar cancelación",cannotCancel:"No se puede cancelar esta reserva",close:"Cerrar",
  confirmingPayment:"Confirmando tu pago…",almostThere:"Ya casi está",confirmationAutomatic:"Esta página se actualiza automáticamente cuando se confirma el pago; normalmente tarda solo unos segundos.",paymentMethodSaved:"Método de pago guardado",allSetForNow:"Todo listo por ahora",savedMethodPrefix:"Hemos guardado tu método de pago de forma segura. Tu tarjeta se cobrará automáticamente el",closerDate:"una fecha cercana a tu llegada",savedMethodSuffix:"antes de tu estancia; no tienes que hacer nada más ahora.",paymentAttention:"El pago requiere atención",cardNotCharged:"No se ha cobrado tu tarjeta",attemptDeclined:"Tu intento de pago fue rechazado.",updatePayment:"Actualizar método de pago",longerExpected:"Está tardando más de lo previsto",waitingConfirmation:"Seguimos esperando la confirmación",checkTripStatus:"Comprobar estado del viaje",bookingConfirmed:"Reserva confirmada",allSet:"Todo listo.",reference:"Referencia",nights:"Noches",bookingStatus:"Estado de la reserva",paymentStatus:"Estado del pago",amountPaid:"Importe pagado",
  previous:"Anterior",next:"Siguiente",manuallyBlocked:"Bloqueado manualmente",bookedByGuest:"Reservado por un huésped",available:"Disponible",paymentFormLoadError:"No se pudo cargar el formulario de pago seguro. No se realizó ningún cobro.",reloadPaymentForm:"Volver a cargar el formulario de pago",testCardNote:"Modo de prueba — utiliza únicamente tarjetas de prueba oficiales de Stripe (p. ej., 4242 4242 4242 4242), nunca una tarjeta real.",backSearch:"Volver a la búsqueda",reviews:"reseñas",bedroom:"dormitorio",bedrooms:"dormitorios",bathroom:"baño",bathrooms:"baños",informationalPrice:"Solo informativo: el total exacto se calcula al reservar.",notChargedYet:"Todavía no se realizará ningún cobro. El precio y la disponibilidad se confirmarán en el siguiente paso.",
  loadingStay:"Cargando alojamiento…",stayNotFound:"Alojamiento no encontrado",mayUnavailable:"Es posible que este alojamiento ya no esté disponible.",loadStayError:"No se pudo cargar este alojamiento. Inténtalo de nuevo más tarde.",stay:"Alojamiento",aboutStay:"Acerca de este alojamiento",checkInOut:"Llegada y salida",checkInFrom:"Llegada a partir de",checkOutBy:"Salida antes de",houseRules:"Normas de la casa",propertyCompliance:"Cumplimiento del alojamiento",ownerEvidenceReviewed:"Pruebas del propietario revisadas",reviewPending:"Revisión pendiente",lastReviewed:"Última revisión",applicableChecks:"comprobaciones aplicables",cancellationPolicy:"Cancellation policy — authoritative English",selectDate:"Seleccionar una fecha",fullName:"Nombre completo",email:"Correo electrónico",cleaningFee:"Tarifa de limpieza",estimatedTotal:"Total estimado",reserving:"Reservando…",reserve:"Reservar",datesBooked:"Otra persona acaba de reservar esas fechas. Elige otras fechas.",createBookingError:"No se pudo crear la reserva. Inténtalo de nuevo.",reachingServerError:"No se pudo contactar con el servidor. Inténtalo de nuevo.",checkIn:"Llegada",checkOut:"Salida",
  save:"Guardar",saved:"Guardado",saveThisStay:"Guardar este alojamiento",removeSavedStay:"Quitar este alojamiento de tus favoritos",saveUpdateError:"No se pudieron actualizar los alojamientos guardados. Inténtalo de nuevo.",
};

const it: GuestDictionary = {
  ...en,
  stays:"Alloggi",changeSearch:"Modifica ricerca",searching:"Ricerca…",invalidSearch:"Ricerca non valida.",loadStaysError:"Impossibile caricare gli alloggi. Riprova più tardi.",noStays:"Nessun alloggio corrisponde alla ricerca. Prova altre date o un'altra destinazione.",night:"notte",guest:"ospite",guests:"ospiti",bed:"letto",beds:"letti",bath:"bagno",baths:"bagni",
  loadingTrips:"Caricamento dei tuoi viaggi…",signInTrips:"Accedi per vedere i tuoi viaggi.",signIn:"Accedi",loadTripsError:"Impossibile caricare i tuoi viaggi. Riprova più tardi.",myTrips:"I miei viaggi",browseDestinations:"Esplora destinazioni",noTrips:"Ancora nessun viaggio.",startExploring:"Esplora gli alloggi.",upcoming:"In programma",past:"Passati",cancelledRefunded:"Annullati / Rimborsati",resumePayment:"Riprendi pagamento",reviewPayment:"Controlla pagamento",viewTrip:"Vedi viaggio",
  loadingCheckout:"Caricamento pagamento…",bookingLoadError:"Impossibile caricare questa prenotazione.",serverError:"Impossibile raggiungere il server.",checkoutStartError:"Impossibile avviare il pagamento.",stripeTest:"Modalità test Stripe",savePaymentMethod:"Salva metodo di pagamento",completeBooking:"Completa prenotazione",deferredChargePrefix:"La carta verrà salvata in modo sicuro e addebitata automaticamente il",immediateSavedCharge:"La carta verrà salvata in modo sicuro e addebitata subito dopo la conferma.",reviewPaymentDetails:"Controlla i dati di pagamento e completa la prenotazione in sicurezza.",loadingPayment:"Caricamento del modulo di pagamento sicuro…",saving:"Salvataggio…",processing:"Elaborazione…",saveCardPay:"Salva carta e paga",payNow:"Paga ora",savePaymentFailed:"Impossibile salvare il metodo di pagamento. Riprova.",paymentFailed:"Pagamento non riuscito. Riprova.",notChargedTodayPrefix:"La carta non verrà addebitata oggi. Verrà addebitata automaticamente il",scheduledDate:"giorno di pagamento previsto",chargedImmediately:"La carta verrà addebitata subito dopo il salvataggio e la conferma.",
  reviewsHeading:"Recensioni",oneReview:"recensione",manyReviews:"recensioni",loadingReviews:"Caricamento recensioni…",loadReviewsError:"Impossibile caricare le recensioni in questo momento.",noReviews:"Ancora nessuna recensione — sii il primo a soggiornare e condividere la tua esperienza.",reviewerGuest:"Ospite",hostResponse:"Risposta dell'host",showMoreReviews:"Mostra altre recensioni",cleanliness:"Pulizia",location:"Posizione",accuracy:"Accuratezza",communication:"Comunicazione",comfort:"Comfort",compliancePending:"Le informazioni di conformità di questo alloggio non sono ancora state esaminate completamente da HOST.",complianceReviewed:"HOST ha esaminato le dichiarazioni e le prove fornite dal proprietario. Il proprietario resta responsabile dell'alloggio e dell'aggiornamento di tutti i controlli.",
  loadingTrip:"Caricamento viaggio…",signInViewTrip:"Accedi per vedere questo viaggio.",tripUnavailable:"Questo viaggio non è disponibile.",loadTripError:"Impossibile caricare questo viaggio. Riprova più tardi.",completePaymentSetup:"Completa configurazione pagamento",priceBreakdown:"Dettaglio prezzo",accommodation:"Alloggio",serviceFee:"Costo del servizio",taxes:"Tasse",totalPaid:"Totale pagato",bookingTotal:"Totale prenotazione",refundStatus:"Stato rimborso",cancelBooking:"Annulla prenotazione",checking:"Verifica…",tripHistory:"Cronologia viaggio",refund:"Rimborso",refundAmount:"Importo rimborso",amountRetained:"Importo trattenuto",keepBooking:"Mantieni prenotazione",cancelling:"Annullamento…",confirmCancellation:"Conferma annullamento",cannotCancel:"Impossibile annullare questa prenotazione",close:"Chiudi",
  confirmingPayment:"Conferma del pagamento…",almostThere:"Ci siamo quasi",confirmationAutomatic:"Questa pagina si aggiorna automaticamente quando il pagamento viene confermato; di solito bastano pochi secondi.",paymentMethodSaved:"Metodo di pagamento salvato",allSetForNow:"Per ora è tutto pronto",savedMethodPrefix:"Abbiamo salvato il metodo di pagamento in modo sicuro. La carta verrà addebitata automaticamente il",closerDate:"una data vicina al check-in",savedMethodSuffix:"prima del soggiorno; non devi fare altro ora.",paymentAttention:"Il pagamento richiede attenzione",cardNotCharged:"La carta non è stata addebitata",attemptDeclined:"Il tentativo di pagamento è stato rifiutato.",updatePayment:"Aggiorna metodo di pagamento",longerExpected:"Sta richiedendo più tempo del previsto",waitingConfirmation:"Siamo ancora in attesa della conferma",checkTripStatus:"Controlla stato del viaggio",bookingConfirmed:"Prenotazione confermata",allSet:"È tutto pronto.",reference:"Riferimento",nights:"Notti",bookingStatus:"Stato prenotazione",paymentStatus:"Stato pagamento",amountPaid:"Importo pagato",
  previous:"Precedente",next:"Successivo",manuallyBlocked:"Bloccato manualmente",bookedByGuest:"Prenotato da un ospite",available:"Disponibile",paymentFormLoadError:"Impossibile caricare il modulo di pagamento sicuro. Non è stato effettuato alcun addebito.",reloadPaymentForm:"Ricarica modulo di pagamento",testCardNote:"Modalità test — usa solo le carte di prova ufficiali Stripe (ad es. 4242 4242 4242 4242), mai una carta reale.",backSearch:"Torna alla ricerca",reviews:"recensioni",bedroom:"camera",bedrooms:"camere",bathroom:"bagno",bathrooms:"bagni",informationalPrice:"Solo a titolo informativo: il totale esatto viene calcolato al momento della prenotazione.",notChargedYet:"Non verrà ancora effettuato alcun addebito. Prezzo e disponibilità saranno confermati nel passaggio successivo.",
  loadingStay:"Caricamento alloggio…",stayNotFound:"Alloggio non trovato",mayUnavailable:"Questo alloggio potrebbe non essere più disponibile.",loadStayError:"Impossibile caricare questo alloggio. Riprova più tardi.",stay:"Alloggio",aboutStay:"Informazioni sull'alloggio",checkInOut:"Check-in e check-out",checkInFrom:"Check-in dalle",checkOutBy:"Check-out entro le",houseRules:"Regole della casa",propertyCompliance:"Conformità dell'alloggio",ownerEvidenceReviewed:"Prove del proprietario esaminate",reviewPending:"Verifica in sospeso",lastReviewed:"Ultima verifica",applicableChecks:"controlli applicabili",cancellationPolicy:"Cancellation policy — authoritative English",selectDate:"Seleziona una data",fullName:"Nome completo",email:"E-mail",cleaningFee:"Costo pulizia",estimatedTotal:"Totale stimato",reserving:"Prenotazione…",reserve:"Prenota",datesBooked:"Queste date sono appena state prenotate da un'altra persona. Scegli altre date.",createBookingError:"Impossibile creare la prenotazione. Riprova.",reachingServerError:"Impossibile raggiungere il server. Riprova.",checkIn:"Check-in",checkOut:"Check-out",
  save:"Salva",saved:"Salvato",saveThisStay:"Salva questo alloggio",removeSavedStay:"Rimuovi questo alloggio dai salvati",saveUpdateError:"Impossibile aggiornare gli alloggi salvati. Riprova.",
};

const nl: GuestDictionary = {
  ...en,
  stays:"Accommodaties",changeSearch:"Zoekopdracht wijzigen",searching:"Zoeken…",invalidSearch:"Ongeldige zoekopdracht.",loadStaysError:"Accommodaties konden niet worden geladen. Probeer het later opnieuw.",noStays:"Geen accommodatie past bij je zoekopdracht. Probeer andere datums of een andere bestemming.",night:"nacht",guest:"gast",guests:"gasten",bed:"bed",beds:"bedden",bath:"badkamer",baths:"badkamers",
  loadingTrips:"Je reizen worden geladen…",signInTrips:"Log in om je reizen te bekijken.",signIn:"Inloggen",loadTripsError:"Je reizen konden niet worden geladen. Probeer het later opnieuw.",myTrips:"Mijn reizen",browseDestinations:"Bestemmingen bekijken",noTrips:"Nog geen reizen.",startExploring:"Bekijk accommodaties.",upcoming:"Aankomend",past:"Voorbij",cancelledRefunded:"Geannuleerd / Terugbetaald",resumePayment:"Betaling hervatten",reviewPayment:"Betaling controleren",viewTrip:"Reis bekijken",
  loadingCheckout:"Betaling laden…",bookingLoadError:"Deze boeking kon niet worden geladen.",serverError:"De server kon niet worden bereikt.",checkoutStartError:"De betaling kon niet worden gestart.",stripeTest:"Stripe-testmodus",savePaymentMethod:"Betaalmethode opslaan",completeBooking:"Boeking afronden",deferredChargePrefix:"Je kaart wordt veilig opgeslagen en automatisch belast op",immediateSavedCharge:"Je kaart wordt veilig opgeslagen en direct na bevestiging voor deze boeking belast.",reviewPaymentDetails:"Controleer je betaalgegevens en rond je boeking veilig af.",loadingPayment:"Beveiligd betaalformulier laden…",saving:"Opslaan…",processing:"Verwerken…",saveCardPay:"Kaart opslaan en betalen",payNow:"Nu betalen",savePaymentFailed:"Je betaalmethode kon niet worden opgeslagen. Probeer het opnieuw.",paymentFailed:"Betaling mislukt. Probeer het opnieuw.",notChargedTodayPrefix:"Je kaart wordt vandaag niet belast. Deze wordt automatisch belast op",scheduledDate:"de geplande betaaldatum",chargedImmediately:"Je kaart wordt direct belast nadat je deze hebt opgeslagen en bevestigd.",
  reviewsHeading:"Beoordelingen",oneReview:"beoordeling",manyReviews:"beoordelingen",loadingReviews:"Beoordelingen laden…",loadReviewsError:"Beoordelingen kunnen nu niet worden geladen.",noReviews:"Nog geen beoordelingen — wees de eerste die verblijft en een ervaring deelt.",reviewerGuest:"Gast",hostResponse:"Reactie van de host",showMoreReviews:"Meer beoordelingen tonen",cleanliness:"Netheid",location:"Locatie",accuracy:"Nauwkeurigheid",communication:"Communicatie",comfort:"Comfort",compliancePending:"De nalevingsinformatie van deze accommodatie is nog niet volledig door HOST beoordeeld.",complianceReviewed:"HOST heeft de verklaringen en bewijsstukken van de eigenaar beoordeeld. De eigenaar blijft verantwoordelijk voor de accommodatie en het actueel houden van alle controles.",
  loadingTrip:"Reis laden…",signInViewTrip:"Log in om deze reis te bekijken.",tripUnavailable:"Deze reis is niet beschikbaar.",loadTripError:"Deze reis kon niet worden geladen. Probeer het later opnieuw.",completePaymentSetup:"Betaalinstelling voltooien",priceBreakdown:"Prijsoverzicht",accommodation:"Accommodatie",serviceFee:"Servicekosten",taxes:"Belastingen",totalPaid:"Totaal betaald",bookingTotal:"Boekingstotaal",refundStatus:"Status terugbetaling",cancelBooking:"Boeking annuleren",checking:"Controleren…",tripHistory:"Reisgeschiedenis",refund:"Terugbetaling",refundAmount:"Terug te betalen bedrag",amountRetained:"Ingehouden bedrag",keepBooking:"Boeking behouden",cancelling:"Annuleren…",confirmCancellation:"Annulering bevestigen",cannotCancel:"Deze boeking kan niet worden geannuleerd",close:"Sluiten",
  confirmingPayment:"Je betaling bevestigen…",almostThere:"Bijna klaar",confirmationAutomatic:"Deze pagina wordt automatisch bijgewerkt zodra je betaling is bevestigd; dit duurt meestal slechts enkele seconden.",paymentMethodSaved:"Betaalmethode opgeslagen",allSetForNow:"Voor nu is alles geregeld",savedMethodPrefix:"We hebben je betaalmethode veilig opgeslagen. Je kaart wordt automatisch belast op",closerDate:"een datum kort voor het inchecken",savedMethodSuffix:"vóór je verblijf; je hoeft nu niets meer te doen.",paymentAttention:"Betaling vereist aandacht",cardNotCharged:"Je kaart is niet belast",attemptDeclined:"Je betalingspoging is geweigerd.",updatePayment:"Betaalmethode bijwerken",longerExpected:"Dit duurt langer dan verwacht",waitingConfirmation:"We wachten nog op bevestiging",checkTripStatus:"Reisstatus controleren",bookingConfirmed:"Boeking bevestigd",allSet:"Alles is geregeld.",reference:"Referentie",nights:"Nachten",bookingStatus:"Boekingsstatus",paymentStatus:"Betalingsstatus",amountPaid:"Betaald bedrag",
  previous:"Vorige",next:"Volgende",manuallyBlocked:"Handmatig geblokkeerd",bookedByGuest:"Geboekt door een gast",available:"Beschikbaar",paymentFormLoadError:"Het beveiligde betaalformulier kon niet worden geladen. Er is niets afgeschreven.",reloadPaymentForm:"Betaalformulier opnieuw laden",testCardNote:"Testmodus — gebruik alleen officiële Stripe-testkaarten (bijv. 4242 4242 4242 4242), nooit een echte kaart.",backSearch:"Terug naar zoeken",reviews:"beoordelingen",bedroom:"slaapkamer",bedrooms:"slaapkamers",bathroom:"badkamer",bathrooms:"badkamers",informationalPrice:"Alleen ter informatie: het exacte totaal wordt bij het boeken berekend.",notChargedYet:"Er wordt nog niets in rekening gebracht. Prijs en beschikbaarheid worden in de volgende stap bevestigd.",
  loadingStay:"Accommodatie laden…",stayNotFound:"Accommodatie niet gevonden",mayUnavailable:"Deze accommodatie is mogelijk niet meer beschikbaar.",loadStayError:"Deze accommodatie kon niet worden geladen. Probeer het later opnieuw.",stay:"Accommodatie",aboutStay:"Over deze accommodatie",checkInOut:"In- en uitchecken",checkInFrom:"Inchecken vanaf",checkOutBy:"Uitchecken voor",houseRules:"Huisregels",propertyCompliance:"Naleving accommodatie",ownerEvidenceReviewed:"Bewijs van eigenaar beoordeeld",reviewPending:"Beoordeling in behandeling",lastReviewed:"Laatst beoordeeld",applicableChecks:"toepasselijke controles",cancellationPolicy:"Cancellation policy — authoritative English",selectDate:"Selecteer een datum",fullName:"Volledige naam",email:"E-mail",cleaningFee:"Schoonmaakkosten",estimatedTotal:"Geschat totaal",reserving:"Reserveren…",reserve:"Reserveren",datesBooked:"Iemand anders heeft deze datums zojuist geboekt. Kies andere datums.",createBookingError:"De boeking kon niet worden aangemaakt. Probeer het opnieuw.",reachingServerError:"De server kon niet worden bereikt. Probeer het opnieuw.",checkIn:"Inchecken",checkOut:"Uitchecken",
  save:"Opslaan",saved:"Opgeslagen",saveThisStay:"Deze accommodatie opslaan",removeSavedStay:"Deze accommodatie uit je opgeslagen lijst verwijderen",saveUpdateError:"Opgeslagen accommodaties konden niet worden bijgewerkt. Probeer het opnieuw.",
};

export function guestDictionary(locale: Locale): GuestDictionary {
  return { en, de, fr, es, it, nl }[locale];
}
