import type { Locale } from "./config";

const en = {
  language: "Language", login: "Log in", signup: "Sign up", trips: "My trips", account: "Account", logout: "Log out", savedStays: "Saved stays", hostWorkspace: "Host workspace",
  dashboard: "Dashboard", bookings: "Bookings", properties: "Properties", reviews: "Reviews",
  eyebrow: "Premium European city stays", heroLead: "Considered stays in Europe's", heroEmphasis: "most storied", heroEnd: "cities.",
  heroBody: "HOST connects discerning guests with exceptional independent accommodation across Europe — from riverside Lisbon apartments to quiet Copenhagen courtyards. Every stay, carefully chosen.",
  destination: "Destination", checkin: "Check-in", checkout: "Check-out", guests: "Guests", search: "Search stays", browse: "Browse destinations",
  where: "Where to stay", firstLook: "A first look at HOST's European cities",
  checkoutMissing: "Add a check-out date.", checkinMissing: "Add a check-in date.", datesInvalid: "Check-out must be after check-in.", guestInvalid: "At least 1 guest is required.",
};

export type MessageKey = keyof typeof en;
type Dictionary = Record<MessageKey, string>;

export const messages: Record<Locale, Dictionary> = {
  en,
  de: { language:"Sprache",login:"Anmelden",signup:"Registrieren",trips:"Meine Reisen",account:"Konto",logout:"Abmelden",savedStays:"Gespeicherte Unterkünfte",hostWorkspace:"Gastgeberbereich",dashboard:"Übersicht",bookings:"Buchungen",properties:"Unterkünfte",reviews:"Bewertungen",eyebrow:"Erstklassige Städtereisen in Europa",heroLead:"Ausgewählte Aufenthalte in Europas",heroEmphasis:"geschichtsträchtigsten",heroEnd:"Städten.",heroBody:"HOST verbindet anspruchsvolle Gäste mit außergewöhnlichen unabhängigen Unterkünften in ganz Europa — von Apartments am Fluss in Lissabon bis zu ruhigen Innenhöfen in Kopenhagen. Jeder Aufenthalt sorgfältig ausgewählt.",destination:"Reiseziel",checkin:"Anreise",checkout:"Abreise",guests:"Gäste",search:"Unterkünfte suchen",browse:"Reiseziele entdecken",where:"Wohin reisen?",firstLook:"Ein erster Blick auf die europäischen Städte von HOST",checkoutMissing:"Fügen Sie ein Abreisedatum hinzu.",checkinMissing:"Fügen Sie ein Anreisedatum hinzu.",datesInvalid:"Die Abreise muss nach der Anreise liegen.",guestInvalid:"Mindestens 1 Gast ist erforderlich." },
  fr: { language:"Langue",login:"Connexion",signup:"S’inscrire",trips:"Mes voyages",account:"Compte",logout:"Déconnexion",savedStays:"Hébergements enregistrés",hostWorkspace:"Espace hôte",dashboard:"Tableau de bord",bookings:"Réservations",properties:"Hébergements",reviews:"Avis",eyebrow:"Séjours haut de gamme dans les villes européennes",heroLead:"Des séjours choisis dans les villes",heroEmphasis:"les plus chargées d’histoire",heroEnd:"d’Europe.",heroBody:"HOST met en relation des voyageurs exigeants avec des hébergements indépendants d’exception partout en Europe — des appartements au bord du Tage à Lisbonne aux cours paisibles de Copenhague. Chaque séjour est choisi avec soin.",destination:"Destination",checkin:"Arrivée",checkout:"Départ",guests:"Voyageurs",search:"Rechercher",browse:"Découvrir les destinations",where:"Où séjourner",firstLook:"Un premier aperçu des villes européennes de HOST",checkoutMissing:"Ajoutez une date de départ.",checkinMissing:"Ajoutez une date d’arrivée.",datesInvalid:"Le départ doit être postérieur à l’arrivée.",guestInvalid:"Au moins 1 voyageur est requis." },
  es: { language:"Idioma",login:"Iniciar sesión",signup:"Registrarse",trips:"Mis viajes",account:"Cuenta",logout:"Cerrar sesión",savedStays:"Alojamientos guardados",hostWorkspace:"Espacio de anfitrión",dashboard:"Panel",bookings:"Reservas",properties:"Alojamientos",reviews:"Reseñas",eyebrow:"Estancias premium en ciudades europeas",heroLead:"Estancias selectas en las ciudades",heroEmphasis:"con más historia",heroEnd:"de Europa.",heroBody:"HOST conecta a huéspedes exigentes con alojamientos independientes excepcionales en toda Europa: desde apartamentos junto al río en Lisboa hasta tranquilos patios en Copenhague. Cada estancia, elegida con cuidado.",destination:"Destino",checkin:"Llegada",checkout:"Salida",guests:"Huéspedes",search:"Buscar estancias",browse:"Explorar destinos",where:"Dónde alojarse",firstLook:"Un primer vistazo a las ciudades europeas de HOST",checkoutMissing:"Añade una fecha de salida.",checkinMissing:"Añade una fecha de llegada.",datesInvalid:"La salida debe ser posterior a la llegada.",guestInvalid:"Se requiere al menos 1 huésped." },
  it: { language:"Lingua",login:"Accedi",signup:"Registrati",trips:"I miei viaggi",account:"Account",logout:"Esci",savedStays:"Soggiorni salvati",hostWorkspace:"Area host",dashboard:"Dashboard",bookings:"Prenotazioni",properties:"Alloggi",reviews:"Recensioni",eyebrow:"Soggiorni premium nelle città europee",heroLead:"Soggiorni selezionati nelle città",heroEmphasis:"più ricche di storia",heroEnd:"d’Europa.",heroBody:"HOST mette in contatto ospiti esigenti con eccezionali alloggi indipendenti in tutta Europa: dagli appartamenti sul fiume a Lisbona ai tranquilli cortili di Copenaghen. Ogni soggiorno è scelto con cura.",destination:"Destinazione",checkin:"Check-in",checkout:"Check-out",guests:"Ospiti",search:"Cerca soggiorni",browse:"Esplora destinazioni",where:"Dove soggiornare",firstLook:"Un primo sguardo alle città europee di HOST",checkoutMissing:"Aggiungi una data di check-out.",checkinMissing:"Aggiungi una data di check-in.",datesInvalid:"Il check-out deve essere successivo al check-in.",guestInvalid:"È richiesto almeno 1 ospite." },
  nl: { language:"Taal",login:"Inloggen",signup:"Registreren",trips:"Mijn reizen",account:"Account",logout:"Uitloggen",savedStays:"Opgeslagen verblijven",hostWorkspace:"Hostomgeving",dashboard:"Dashboard",bookings:"Boekingen",properties:"Accommodaties",reviews:"Beoordelingen",eyebrow:"Hoogwaardige verblijven in Europese steden",heroLead:"Zorgvuldig gekozen verblijven in Europa's",heroEmphasis:"meest historische",heroEnd:"steden.",heroBody:"HOST brengt veeleisende gasten samen met uitzonderlijke onafhankelijke accommodaties in heel Europa — van appartementen aan de rivier in Lissabon tot rustige binnenplaatsen in Kopenhagen. Elk verblijf zorgvuldig gekozen.",destination:"Bestemming",checkin:"Inchecken",checkout:"Uitchecken",guests:"Gasten",search:"Verblijven zoeken",browse:"Bestemmingen bekijken",where:"Waar verblijven",firstLook:"Een eerste blik op de Europese steden van HOST",checkoutMissing:"Voeg een uitcheckdatum toe.",checkinMissing:"Voeg een incheckdatum toe.",datesInvalid:"Uitchecken moet na inchecken zijn.",guestInvalid:"Minimaal 1 gast is vereist." },
};
